import:
  - ~/.dracula.alacritty.yml

window:
  # dimensions:
  #   columns: 148
  #   lines: 36
  padding:
    x: 8
    y: 4
  opacity: 0.92
  startup_mode: Maximized
  decorations: full
  option_as_alt: Both

scrolling:
  history: 10000
  multiplier: 5

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Medium
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: BoldItalic
  size: 14
  offset:
    x: 1
    y: 1

cursor:
  style:
    shape: Block
    blinking: Off

selection:
  save_to_clipboard: true

key_bindings:
  # (Windows, Linux, and BSD only)
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: F11, mods: None, action: ToggleFullscreen }
  - { key: Equals, mods: Command, action: IncreaseFontSize }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - { key: L, mods: Command, action: ClearLogNotice }
  - { key: L, mods: Command, chars: "\x0c" }
  - { key: T, mods: Command, action: SpawnNewInstance }
  - { key: C, mods: Command|Shift, chars: "\x03" }
  - { key: F, mods: Command|Shift, action: ReceiveChar }
