import:
  - ~/.dracula.alacritty.yml

window:
  dimensions:
    columns: 132
    lines: 36
  padding:
    x: 10
    y: 5
  opacity: 0.98

scrolling:
  history: 10000
  multiplier: 5

font:
  normal:
    family: JetBrains Mono Nerd Font
    style: Medium
  bold:
    family: JetBrains Mono Nerd Font
    style: Bold
  bold_italic:
    family: JetBrains Mono Nerd Font
    style: BoldItalic
  Italic:
    family: JetBrains Mono Nerd Font
    style: MediumItalic
  size: 14
  offset:
    x: 1
    y: 1

cursor:
  style:
    shape: Block
    blinking: Off

selection:
  save_to_clipboard: true

key_bindings:
    # (Windows, Linux, and BSD only)
  - { key: V,         mods: Control,       action: Paste                       }
  - { key: C,         mods: Control,       action: Copy                        }
  - { key: F11,       mods: None,          action: ToggleFullscreen            }
  - { key: Key0,      mods: Control,       action: ResetFontSize               }
  - { key: Equals,    mods: Control,       action: IncreaseFontSize            }
  - { key: Minus,     mods: Control,       action: DecreaseFontSize            }
  - { key: L,         mods: Control,       action: ClearLogNotice              }
  - { key: L,         mods: Control,       chars: "\x0c"                       }
  - { key: T,         mods: Control,       action: SpawnNewInstance            }
  - { key: W,         mods: Control,       action: Quit                        }
  - { key: C,         mods: Control|Shift, chars: "\x03"                       }
  - { key: F,         mods: Control|Shift, action: ReceiveChar                 }

