require("joaovfsousa.plugins.telescope").setup()
require("joaovfsousa.plugins.which-key")
require("joaovfsousa.plugins.nvimtree").setup()
require("joaovfsousa.plugins.bufferline").setup()
require("joaovfsousa.plugins.lualine").setup()
require("joaovfsousa.plugins.jester").setup()
require("joaovfsousa.plugins.gitsigns").setup()
