require("joaovfsousa.lazy")
require("joaovfsousa.lsp")
require("joaovfsousa.options")
require("joaovfsousa.theme")
require("joaovfsousa.plugins")
require("joaovfsousa.keymaps")
require("joaovfsousa.commands")
